apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask2.fullname" . }}-mysql
  labels:
    app: {{- include "flask2.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flask2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flask2.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-mysql
          image: "{{ .Values.dbImage.repository }}:{{ .Values.dbImage.tag }}"
          resources:
            {{- toYaml .Values.dbResources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.dbPort }}
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.env.db.mysql_root_password }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.db.mysql_password }}
            - name: MYSQL_USER
              value: {{ .Values.env.db.mysql_user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.db.mysql_db }}
