apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask2.fullname" .}}-mysql-pvc
  labels:
    app: {{- include "flask2.labels" . | nindent 4}}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.db.storage }}
