apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask2.fullname" }}-mysql
spec:
  selector:
    app: {{ include "flask2.fullname" }}-mysql
  ports:
    - name: http
      port: {{ .Values.service.dbPort }}
      targetPort: {{ .Values.service.dbPort }}
      protocol: TCP
