apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask2.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "flask2.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if  .Values.service.type eq "NodePort"}}
      nodePort: {{.Values.service.nodePort}}
      {{- end}}
